# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Python\demo-exam-test\app\ui\ErrorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(268, 118)
        Dialog.setStyleSheet("background: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_field = QtWidgets.QTextEdit(Dialog)
        self.error_field.setStyleSheet("QTextEdit {\n"
"background: none;\n"
"border: none;\n"
"}")
        self.error_field.setReadOnly(True)
        self.error_field.setObjectName("error_field")
        self.verticalLayout.addWidget(self.error_field)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
