# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Python\demo-exam-test\app\ui\MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 600)
        Dialog.setMinimumSize(QtCore.QSize(350, 600))
        Dialog.setStyleSheet("background: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_field = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_field.sizePolicy().hasHeightForWidth())
        self.login_field.setSizePolicy(sizePolicy)
        self.login_field.setMinimumSize(QtCore.QSize(70, 0))
        self.login_field.setMaximumSize(QtCore.QSize(16777215, 30))
        self.login_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_field.setText("")
        self.login_field.setAlignment(QtCore.Qt.AlignCenter)
        self.login_field.setObjectName("login_field")
        self.horizontalLayout.addWidget(self.login_field)
        self.search_field = QtWidgets.QLineEdit(Dialog)
        self.search_field.setStyleSheet("QLineEdit {\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"padding: 10px;\n"
"}")
        self.search_field.setObjectName("search_field")
        self.horizontalLayout.addWidget(self.search_field)
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setStyleSheet("QPushButton {\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"padding: 10px;\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.search_field.setPlaceholderText(_translate("Dialog", "Введите название таблицы"))
        self.search_btn.setText(_translate("Dialog", "Поиск"))
        self.tableWidget.setSortingEnabled(True)
